[component]
structures = [ "content_blocks" ]
label = "Services"
description = "Projects Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Services"
description_html = "Let's see some of my main services"
link_url = "/services"
show_projects = true